assembly:
- mousetrap.plugins.camera.CameraPlugin
- mousetrap.plugins.display.DisplayPlugin
- mousetrap.plugins.nose_joystick.NoseJoystickPlugin
- mousetrap.plugins.eyes.EyesPlugin
camera:
  device_index: -1
  height: 300
  width: 400
classes:
  mousetrap.plugins.display.DisplayPlugin:
    window_title: MouseTrap
  mousetrap.plugins.eyes.ClosedDetector:
    max_samples: 15
    min_fraction_to_be_closed: 0.8
  mousetrap.plugins.eyes.LeftEyeLocator:
    face_detector:
      min_neighbors: 5
      scale_factor: 1.5
    left_eye_detector:
      min_neighbors: 10
      scale_factor: 1.5
    open_eye_detector:
      min_neighbors: 3
      scale_factor: 1.1
  mousetrap.plugins.eyes.MotionDetector:
    max_samples: 5
  mousetrap.plugins.nose.NoseLocator:
    face_detector:
      min_neighbors: 5
      scale_factor: 1.5
    nose_detector:
      min_neighbors: 5
      scale_factor: 1.1
  mousetrap.plugins.nose_joystick.NoseJoystickPlugin:
    threshold: 5
haar_files:
  face: haars/haarcascade_frontalface_default.xml
  left_eye: haars/haarcascade_mcs_lefteye.xml
  nose: haars/haarcascade_mcs_nose.xml
  open_eye: haars/haarcascade_eye.xml
logging:
  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
      stream: ext://sys.stdout
  root:
    formatters:
    - default
    handlers:
    - console
    level: DEBUG
  version: 1
loops_per_second: 10
